parser:
  src:
    - ./Depot Abrechnungen/ScalableRaw
    #- ./missing/
  datereadformat: "%d.%m.%Y"
  datewriteformat: "%Y%m%d"
  targetpath: ./
  error_log: ./error.log
  log_level: error
  overwrite: True
